wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.15.12
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1698935534.271293
    t:
      1:
      - 53
      - 55
      2:
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.8.18
      5: 0.15.12
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
    session_history: code/_session_history.ipynb
