name: mlflow-61aab3aca5422098806cb27c174c39ca8c0aee8a
channels:
  - conda-forge
  - defaults
dependencies:
  - alembic=1.12.1=pyhd8ed1ab_0
  - aws-c-auth=0.7.5=he6edc6d_0
  - aws-c-cal=0.6.7=ha251d5a_0
  - aws-c-common=0.9.4=h93a5062_0
  - aws-c-compression=0.2.17=ha251d5a_4
  - aws-c-event-stream=0.3.2=hd73d0d5_4
  - aws-c-http=0.7.13=hb3e5a72_7
  - aws-c-io=0.13.35=h0f79f92_4
  - aws-c-mqtt=0.9.8=he2964ae_0
  - aws-c-s3=0.3.20=h8d12f51_1
  - aws-c-sdkutils=0.1.12=ha251d5a_3
  - aws-checksums=0.1.17=ha251d5a_3
  - aws-crt-cpp=0.24.4=h5f3d163_2
  - aws-sdk-cpp=1.11.182=hba14a0b_2
  - bcrypt=4.0.1=py39haff01fd_1
  - blinker=1.6.3=pyhd8ed1ab_0
  - brotli=1.1.0=hb547adb_1
  - brotli-bin=1.1.0=hb547adb_1
  - brotli-python=1.1.0=py39hb198ff7_1
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.20.1=h93a5062_1
  - ca-certificates=2023.7.22=hf0a4a13_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.16.0=py39he153c15_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - configparser=5.3.0=pyhd8ed1ab_0
  - contourpy=1.1.1=py39hbd775c9_1
  - cryptography=41.0.5=py39h4720a30_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - databricks-cli=0.18.0=pyhd8ed1ab_0
  - docker-py=6.1.3=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - flask=2.3.3=pyhd8ed1ab_0
  - fonttools=4.43.1=py39h17cfd9d_0
  - freetype=2.12.1=hadb7bae_2
  - gflags=2.2.2=hc88da5d_1004
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.40=pyhd8ed1ab_0
  - glog=0.6.0=h6da1cb0_0
  - greenlet=3.0.1=py39h4ce5507_0
  - gunicorn=21.2.0=py39h2804cbe_1
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib-resources=6.1.0=pyhd8ed1ab_0
  - importlib_resources=6.1.0=pyhd8ed1ab_0
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=h1a8c8d9_3
  - kiwisolver=1.4.5=py39hbd775c9_1
  - krb5=1.21.2=h92f50d5_0
  - lcms2=2.12=had6a04f_0
  - lerc=3.0=hbdafb3b_0
  - libabseil=20230802.1=cxx17_h13dd4ca_0
  - libarrow=13.0.0=h87fad27_13_cpu
  - libblas=3.9.0=19_osxarm64_openblas
  - libbrotlicommon=1.1.0=hb547adb_1
  - libbrotlidec=1.1.0=hb547adb_1
  - libbrotlienc=1.1.0=hb547adb_1
  - libcblas=3.9.0=19_osxarm64_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.4.0=h2d989ff_0
  - libcxx=16.0.6=h4653b0c_0
  - libdeflate=1.10=h3422bc3_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libevent=2.1.12=h2757513_1
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=13_2_0_hd922786_1
  - libgfortran5=13.2.0=hf226fd6_1
  - libgoogle-cloud=2.12.0=h5a37b55_3
  - libgrpc=1.58.2=h19be7b0_0
  - liblapack=3.9.0=19_osxarm64_openblas
  - libnghttp2=1.55.1=h2b02ca0_0
  - libopenblas=0.3.24=openmp_hd76b1f2_0
  - libpng=1.6.39=h76d750c_0
  - libprotobuf=4.24.3=hf590ac1_1
  - libre2-11=2023.06.02=h1753957_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.44.0=h091b4b1_0
  - libssh2=1.11.0=h7a5bd25_0
  - libthrift=0.19.0=h026a170_1
  - libtiff=4.3.0=h2810ee2_4
  - libutf8proc=2.8.0=h1a8c8d9_0
  - libwebp-base=1.3.2=hb547adb_0
  - libzlib=1.2.13=h53f4e23_5
  - llvm-openmp=17.0.4=hcd81f8e_0
  - lz4-c=1.9.4=hb7217d7_0
  - mako=1.2.4=pyhd8ed1ab_0
  - markdown=3.5.1=pyhd8ed1ab_0
  - markupsafe=2.1.3=py39h0f82c59_1
  - matplotlib=3.8.1=py39hdf13c20_0
  - matplotlib-base=3.8.1=py39h1a09f3e_0
  - mlflow=2.8.0=py39h3c3ad29_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=h463b476_2
  - numpy=1.26.0=py39hc348b60_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.5.0=hd370e0e_0
  - openssl=3.1.4=h0d3ecfb_0
  - orc=1.9.0=hcd02cb2_3
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=1.2.3=py39ha4bedbf_0
  - paramiko=3.3.1=pyhd8ed1ab_0
  - pillow=8.1.2=py39h282ff46_1
  - pip=20.3.3=pyhd8ed1ab_0
  - prometheus_client=0.18.0=pyhd8ed1ab_0
  - prometheus_flask_exporter=0.23.0=pyhd8ed1ab_0
  - protobuf=4.24.3=py39h6b23cf8_1
  - psutil=5.9.5=py39h0f82c59_1
  - pyarrow=13.0.0=py39h5c469ea_13_cpu
  - pycparser=2.21=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_0
  - pynacl=1.5.0=py39h0f82c59_3
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.18=hfa1ae8a_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=4_cp39
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pywin32-on-windows=0.1.0=pyh1179c8e_3
  - pyyaml=6.0.1=py39h0f82c59_1
  - querystring_parser=1.2.4=py_0
  - re2=2023.06.02=h6135d0a_0
  - readline=8.2=h92ec313_1
  - requests=2.31.0=pyhd8ed1ab_0
  - scikit-learn=1.3.2=py39h172c841_1
  - scipy=1.11.3=py39h89ddb1b_1
  - setuptools=59.8.0=py39h2804cbe_1
  - six=1.16.0=pyh6c4a22f_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.1.10=h17c5cce_0
  - sqlalchemy=2.0.22=py39h17cfd9d_0
  - sqlparse=0.4.4=pyhd8ed1ab_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tk=8.6.13=hb31c410_0
  - tornado=6.3.3=py39h0f82c59_1
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - unicodedata2=15.1.0=py39h0f82c59_0
  - urllib3=2.0.7=pyhd8ed1ab_0
  - websocket-client=1.6.4=pyhd8ed1ab_0
  - werkzeug=3.0.1=pyhd8ed1ab_0
  - wheel=0.41.3=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h53f4e23_5
  - zstd=1.5.5=h4f39d0f_0
  - pip:
      - docker-pycreds==0.4.0
      - pathtools==0.1.2
      - promise==2.3
      - sentry-sdk==1.33.1
      - shortuuid==1.0.11
      - subprocess32==3.5.4
      - wandb==0.10.31
prefix: /Users/saurabhbhardwaj/anaconda3/envs/mlflow-61aab3aca5422098806cb27c174c39ca8c0aee8a
